apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: harman-system

resources:
  - ../../base

patchesStrategicMerge:
  - daemonset-patch.yaml
  - configmap-patch.yaml

images:
  - name: harman-collector
    newTag: dev

commonLabels:
  environment: dev

