apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: harman-system

resources:
  - daemonset.yaml
  - configmap.yaml
  - secret.yaml

commonLabels:
  app: file-collector
  managed-by: kustomize

